[package]
name = "lbj"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
itertools = "0.11.0"
pest = "2.7.1"
pest_derive = "2.7.1"
petgraph = "0.6.3"
thiserror = "1.0.44"
